"""add_processed_payments_table

Revision ID: 57d55504e53e
Revises: b500888a0d58
Create Date: 2026-05-19 21:51:52.386501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d55504e53e'
down_revision: Union[str, Sequence[str], None] = 'b500888a0d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_payments_id'), 'processed_payments', ['id'], unique=False)
    op.create_index(op.f('ix_processed_payments_razorpay_order_id'), 'processed_payments', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_processed_payments_razorpay_payment_id'), 'processed_payments', ['razorpay_payment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_payments_razorpay_payment_id'), table_name='processed_payments')
    op.drop_index(op.f('ix_processed_payments_razorpay_order_id'), table_name='processed_payments')
    op.drop_index(op.f('ix_processed_payments_id'), table_name='processed_payments')
    op.drop_table('processed_payments')
    # ### end Alembic commands ###
