"""Add audio_interviews_left_this_month

Revision ID: 6870c5a53c16
Revises: 39e36b6de8f0
Create Date: 2026-05-10 19:34:29.948601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6870c5a53c16'
down_revision: Union[str, Sequence[str], None] = '39e36b6de8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('audio_interviews_left_this_month', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'audio_interviews_left_this_month')
    # ### end Alembic commands ###
