"""add last_audio_interview_at column

Revision ID: 6c561be3166b
Revises: f2d7c8e9a1b2
Create Date: 2026-05-20 17:52:42.207447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c561be3166b'
down_revision: Union[str, Sequence[str], None] = 'f2d7c8e9a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_payments_razorpay_order_id'), table_name='processed_payments')
    op.create_index(op.f('ix_processed_payments_razorpay_order_id'), 'processed_payments', ['razorpay_order_id'], unique=True)
    op.add_column('users', sa.Column('last_audio_interview_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_audio_interview_at')
    op.drop_index(op.f('ix_processed_payments_razorpay_order_id'), table_name='processed_payments')
    op.create_index(op.f('ix_processed_payments_razorpay_order_id'), 'processed_payments', ['razorpay_order_id'], unique=False)
    # ### end Alembic commands ###
