"""Added subscription system and usage tracking

Revision ID: 755f00d50567
Revises: 03d02b439147
Create Date: 2025-07-29 01:53:23.187897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755f00d50567'
down_revision: Union[str, Sequence[str], None] = '03d02b439147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('max_ats_checks', sa.Integer(), nullable=False),
    sa.Column('max_resume_tailoring', sa.Integer(), nullable=False),
    sa.Column('max_mock_interviews', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('users', sa.Column('subscription_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('ats_checks_left_today', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('resume_tailoring_left_this_week', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('mock_interviews_left_this_month', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_ats_check_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_resume_tailoring_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_mock_interview_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'users', 'subscription_plans', ['subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'last_mock_interview_at')
    op.drop_column('users', 'last_resume_tailoring_at')
    op.drop_column('users', 'last_ats_check_at')
    op.drop_column('users', 'mock_interviews_left_this_month')
    op.drop_column('users', 'resume_tailoring_left_this_week')
    op.drop_column('users', 'ats_checks_left_today')
    op.drop_column('users', 'subscription_id')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
