"""add warnings_count to interview_sessions

Revision ID: b507176f4d1e
Revises: 653eb5651cf9
Create Date: 2026-05-16 16:19:47.295145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b507176f4d1e'
down_revision: Union[str, Sequence[str], None] = '653eb5651cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('warnings_count', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'warnings_count')
    # ### end Alembic commands ###
