"""Add purchased credits and fix mock default

Revision ID: e35581d9474a
Revises: 4e83c51d279a
Create Date: 2026-05-11 23:01:12.795417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e35581d9474a'
down_revision: Union[str, Sequence[str], None] = '4e83c51d279a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('purchased_ats_credits', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('purchased_tailor_credits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'purchased_tailor_credits')
    op.drop_column('users', 'purchased_ats_credits')
    # ### end Alembic commands ###
